<?php

return [
    'resellers' => [
        'title' => app_text('auto.k_32cea47742bf'),
        'table' => 'resellers',
        'columns' => ['id', 'parent_reseller_id', 'subscription_plan_id', 'name', 'email', 'phone', 'legal_name', 'legal_status', 'legal_inn', 'legal_address', 'referral_code', 'manager_limit', 'direct_leader_limit', 'branch_leader_limit', 'direct_manager_limit', 'branch_manager_limit', 'per_child_manager_limit', 'price_per_leader', 'price_per_consultant', 'is_active'],
        'fields' => [
            'parent_reseller_id' => ['label' => 'Вышестоящий лидер', 'type' => 'select', 'source' => 'resellers', 'nullable' => true],
            'template_id' => [
                'label' => 'Шаблон мини-сайта',
                'type' => 'select',
                'source' => 'site_templates',
                'nullable' => true,
                'nullable_label' => 'Как у вышестоящего лидера',
                'virtual' => true,
                'hint' => 'Этот пункт применяет мини-сайт вышестоящего лидера. Выберите шаблон только если нужна отдельная стартовая страница.',
            ],
            'name' => ['label' => 'Имя в системе', 'required' => true, 'hint' => 'Короткое имя для таблиц, меню и списков. Например: Мария Викторова.'],
            'email' => ['label' => 'Email', 'type' => 'email', 'hint' => 'Используется для связи с лидером и счетов.'],
            'phone' => ['label' => app_text('auto.k_87ec4b495b56')],
            'legal_name' => ['label' => 'ФИО / наименование плательщика', 'hint' => 'Реквизиты самого лидера для счетов и договорных отношений с SWPro. Лидер не является оператором персональных данных SWPro.'],
            'legal_status' => ['label' => 'Правовой статус плательщика', 'hint' => 'Например: плательщик налога на профессиональный доход или индивидуальный предприниматель.'],
            'legal_inn' => ['label' => 'ИНН плательщика'],
            'legal_address' => ['label' => 'Адрес плательщика'],
            'subscription_plan_id' => [
                'label' => 'Подписка',
                'type' => 'select',
                'source' => 'subscription_plans',
                'nullable' => true,
                'nullable_label' => 'Нет подписки',
                'hint' => 'Лимиты и стоимость берутся из выбранной подписки. Тарифы настраиваются в разделе «Подписка».',
            ],
            'referral_code' => ['label' => app_text('auto.k_a9d3a61b02f2'), 'required' => true, 'hint' => 'Код можно менять: старые ссылки продолжат работать и приведут на новый код.'],
            'is_active' => ['label' => app_text('auto.k_667904ef22a4'), 'type' => 'checkbox', 'default' => 1],
        ],
    ],
    'managers' => [
        'title' => app_text('auto.k_6756aa53b5b5'),
        'table' => 'managers',
        'columns' => ['id', 'reseller_id', 'name', 'email', 'phone', 'referral_code', 'is_active'],
        'fields' => [
            'reseller_id' => ['label' => app_text('auto.k_86469fea3a4a'), 'type' => 'select', 'source' => 'resellers', 'nullable' => true],
            'template_id' => [
                'label' => 'Шаблон мини-сайта',
                'type' => 'select',
                'source' => 'site_templates',
                'nullable' => true,
                'nullable_label' => 'Как у лидера',
                'virtual' => true,
                'hint' => 'Этот пункт применяет мини-сайт выбранного лидера. Выберите шаблон только если нужна отдельная стартовая страница.',
            ],
            'name' => ['label' => app_text('auto.k_aee78fe86022'), 'required' => true],
            'email' => ['label' => 'Email', 'type' => 'email'],
            'phone' => ['label' => app_text('auto.k_87ec4b495b56')],
            'telegram_id' => ['label' => 'Telegram ID'],
            'max_id' => ['label' => 'MAX ID'],
            'vk_id' => ['label' => 'VK ID'],
            'referral_code' => ['label' => app_text('auto.k_a9d3a61b02f2'), 'required' => true, 'hint' => 'Код можно менять: старые ссылки продолжат работать и приведут на новый код.'],
            'is_active' => ['label' => app_text('auto.k_667904ef22a4'), 'type' => 'checkbox', 'default' => 1],
        ],
    ],
    'users' => [
        'title' => 'Клиенты',
        'table' => 'end_users',
        'columns' => ['id', 'platform', 'platform_user_id', 'username', 'reseller_id', 'manager_id', 'status'],
        'fields' => [
            'reseller_id' => ['label' => app_text('auto.k_86469fea3a4a'), 'type' => 'select', 'source' => 'resellers', 'nullable' => true],
            'manager_id' => ['label' => app_text('auto.k_8d98911527e4'), 'type' => 'select', 'source' => 'managers', 'nullable' => true],
            'platform' => ['label' => app_text('auto.k_89009febe5c6'), 'type' => 'select', 'options' => ['telegram', 'VK', 'OK', 'MAX', 'web'], 'required' => true],
            'platform_user_id' => ['label' => app_text('auto.k_c7f40b63aad7'), 'required' => true],
            'username' => ['label' => 'Username'],
            'first_name' => ['label' => app_text('auto.k_aee78fe86022')],
            'last_name' => ['label' => app_text('auto.k_5aa7f892d573')],
            'gender' => ['label' => 'Пол', 'type' => 'select', 'options' => ['female', 'male', 'prefer_not_to_say'], 'nullable' => true],
            'birth_date' => ['label' => 'Дата рождения', 'type' => 'date', 'nullable' => true],
            'age_years' => ['label' => 'Возраст', 'type' => 'number', 'nullable' => true],
            'city' => ['label' => 'Город'],
            'timezone' => ['label' => 'Часовой пояс'],
            'phone' => ['label' => app_text('auto.k_87ec4b495b56')],
            'email' => ['label' => 'Email', 'type' => 'email'],
            'referral_code_used' => ['label' => app_text('auto.k_23f8d055a5d6')],
            'client_stage' => ['label' => 'Этап клиента', 'type' => 'select', 'options' => array_keys(client_stage_labels()), 'required' => true],
            'notifications_enabled' => ['label' => 'Разрешены сообщения', 'type' => 'checkbox', 'default' => 1],
            'status' => ['label' => app_text('auto.k_f7f293b5c58c'), 'type' => 'select', 'options' => ['active', 'blocked', 'unsubscribed'], 'required' => true],
        ],
    ],
    'platform_accounts' => [
        'title' => app_text('auto.k_68a410fd6049'),
        'table' => 'platform_accounts',
        'columns' => ['id', 'end_user_id', 'platform', 'platform_user_id', 'username'],
        'fields' => [
            'end_user_id' => ['label' => app_text('auto.k_51aff1853949'), 'type' => 'select', 'source' => 'end_users', 'required' => true],
            'platform' => ['label' => app_text('auto.k_89009febe5c6'), 'type' => 'select', 'options' => ['telegram', 'VK', 'OK', 'MAX', 'web'], 'required' => true],
            'platform_user_id' => ['label' => app_text('auto.k_c7f40b63aad7'), 'required' => true],
            'username' => ['label' => 'Username'],
        ],
    ],
    'leads' => [
        'title' => app_text('auto.k_be11d71726a6'),
        'table' => 'leads',
        'columns' => ['id', 'end_user_id', 'manager_id', 'reseller_id', 'product_id', 'request_type', 'source_platform', 'status', 'created_at'],
        'fields' => [
            'end_user_id' => ['label' => app_text('auto.k_51aff1853949'), 'type' => 'select', 'source' => 'end_users', 'required' => true],
            'manager_id' => ['label' => app_text('auto.k_8d98911527e4'), 'type' => 'select', 'source' => 'managers', 'nullable' => true],
            'reseller_id' => ['label' => app_text('auto.k_86469fea3a4a'), 'type' => 'select', 'source' => 'resellers', 'nullable' => true],
            'product_id' => ['label' => app_text('auto.k_82a9ca014bb8'), 'type' => 'select', 'source' => 'products', 'nullable' => true],
            'request_type' => [
                'label' => 'Тип обращения',
                'type' => 'select',
                'options' => ['consultation', 'product', 'test_result', 'cashback', 'cooperation', 'other'],
                'required' => true,
            ],
            'source_platform' => ['label' => app_text('auto.k_89009febe5c6'), 'type' => 'select', 'options' => ['telegram', 'VK', 'OK', 'MAX', 'web'], 'required' => true],
            'message' => ['label' => app_text('auto.k_dc72346ac447'), 'type' => 'textarea'],
            'status' => ['label' => app_text('auto.k_f7f293b5c58c'), 'type' => 'select', 'options' => ['new', 'contacted', 'interested', 'closed', 'lost'], 'required' => true],
        ],
    ],
    'categories' => [
        'title' => app_text('auto.k_f7d9b1c868fa'),
        'table' => 'product_categories',
        'columns' => ['id', 'title', 'slug', 'sort_order', 'is_active'],
        'fields' => [
            'title' => ['label' => app_text('auto.k_3de49828e86a'), 'required' => true],
            'slug' => ['label' => 'Slug', 'required' => true],
            'description' => ['label' => app_text('auto.k_f5441f6aee76'), 'type' => 'textarea'],
            'sort_order' => ['label' => app_text('auto.k_ed030118aad8'), 'type' => 'number', 'default' => 100],
            'is_active' => ['label' => app_text('auto.k_c1ae516375c4'), 'type' => 'checkbox', 'default' => 1],
        ],
    ],
    'products' => [
        'title' => app_text('auto.k_c85756a1ae45'),
        'table' => 'products',
        'columns' => ['id', 'category_id', 'title', 'slug', 'price', 'is_active'],
        'fields' => [
            'category_id' => ['label' => app_text('auto.k_1cf49d95b0ed'), 'type' => 'select', 'source' => 'product_categories', 'nullable' => true],
            'title' => ['label' => app_text('auto.k_3de49828e86a'), 'required' => true],
            'slug' => ['label' => 'Slug', 'required' => true],
            'short_description' => ['label' => app_text('auto.k_d1b43352dd0b'), 'type' => 'textarea'],
            'full_description' => ['label' => app_text('auto.k_a6c29f1af453'), 'type' => 'textarea'],
            'composition' => ['label' => app_text('auto.k_c37407200657'), 'type' => 'textarea'],
            'usage_text' => ['label' => app_text('auto.k_1f14ddbb7157'), 'type' => 'textarea'],
            'warning_text' => ['label' => app_text('auto.k_e48b13edc15f'), 'type' => 'textarea'],
            'contraindications' => ['label' => app_text('auto.k_b4307011a15a'), 'type' => 'textarea'],
            'image_path' => ['label' => app_text('auto.k_56a1fd52891d'), 'type' => 'file', 'accept' => 'image/*'],
            'document_path' => ['label' => app_text('auto.k_2f76dff0da9f'), 'type' => 'file', 'accept' => 'application/pdf'],
            'video_url' => ['label' => app_text('auto.k_54fbfaf96a2d')],
            'price' => ['label' => app_text('auto.k_367e2792c179'), 'type' => 'number', 'step' => '0.01', 'nullable' => true],
            'purchase_url' => ['label' => app_text('auto.k_ab281ec27935')],
            'sort_order' => ['label' => app_text('auto.k_ed030118aad8'), 'type' => 'number', 'default' => 100],
            'is_active' => ['label' => app_text('auto.k_667904ef22a4'), 'type' => 'checkbox', 'default' => 1],
        ],
    ],
    'tests' => [
        'title' => app_text('auto.k_663c94d30018'),
        'table' => 'tests',
        'columns' => ['id', 'title', 'category_id', 'scoring_type', 'is_active', 'sort_order'],
        'fields' => [
            'title' => ['label' => app_text('auto.k_3de49828e86a'), 'required' => true],
            'description' => ['label' => app_text('auto.k_f5441f6aee76'), 'type' => 'textarea'],
            'category_id' => ['label' => app_text('auto.k_19c85838e63f'), 'type' => 'select', 'source' => 'product_categories', 'nullable' => true],
            'scoring_type' => ['label' => 'Тип теста', 'type' => 'select', 'options' => ['single', 'multiscale'], 'required' => true],
            'emoji' => ['label' => 'Emoji'],
            'intro_text' => ['label' => 'Текст перед стартом', 'type' => 'textarea'],
            'intro_image_path' => ['label' => 'Картинка intro', 'type' => 'file', 'accept' => 'image/*'],
            'intro_video_url' => ['label' => 'Видео intro'],
            'sort_order' => ['label' => app_text('auto.k_ed030118aad8'), 'type' => 'number', 'default' => 100],
            'is_active' => ['label' => app_text('auto.k_667904ef22a4'), 'type' => 'checkbox', 'default' => 1],
        ],
    ],
    'broadcasts' => [
        'title' => app_text('auto.k_08a679f215bd'),
        'table' => 'broadcasts',
        'columns' => ['id', 'title', 'platform', 'target_type', 'scheduled_at', 'status'],
        'fields' => [
            'title' => ['label' => app_text('auto.k_3de49828e86a'), 'required' => true],
            'message_text' => ['label' => app_text('auto.k_1ba376a71bcf'), 'type' => 'textarea'],
            'audience_type' => ['label' => 'Получатели', 'type' => 'select', 'options' => ['clients', 'consultants'], 'required' => true],
            'image_path' => ['label' => app_text('auto.k_56a1fd52891d'), 'type' => 'file', 'accept' => 'image/*'],
            'video_path' => ['label' => 'Видео MP4', 'type' => 'file', 'accept' => 'video/mp4'],
            'button_text' => ['label' => app_text('auto.k_f9fd27363780')],
            'button_url' => ['label' => app_text('auto.k_668acad1ed4c')],
            'target_type' => ['label' => app_text('auto.k_e9476ab1820b'), 'type' => 'select', 'options' => ['all', 'reseller', 'manager', 'segment', 'own_clients', 'branch_clients', 'direct_consultants', 'branch_consultants', 'direct_leaders', 'branch_leaders', 'whole_branch'], 'required' => true],
            'target_reseller_id' => ['label' => app_text('auto.k_86469fea3a4a'), 'type' => 'select', 'source' => 'resellers', 'nullable' => true],
            'target_manager_id' => ['label' => app_text('auto.k_8d98911527e4'), 'type' => 'select', 'source' => 'managers', 'nullable' => true],
            'segment_stage' => ['label' => 'Сегмент: этап клиента', 'type' => 'select', 'options' => array_keys(client_stage_labels()), 'nullable' => true],
            'segment_checkup' => ['label' => 'Сегмент: чек-ап', 'type' => 'select', 'options' => ['not_started', 'started', 'completed'], 'nullable' => true],
            'segment_activity' => ['label' => 'Сегмент: активность', 'type' => 'select', 'options' => ['active_7', 'active_30', 'inactive_14', 'inactive_30'], 'nullable' => true],
            'platform' => ['label' => app_text('auto.k_89009febe5c6'), 'type' => 'select', 'options' => ['all', 'telegram', 'VK', 'OK', 'MAX'], 'required' => true],
            'schedule_type' => ['label' => app_text('auto.k_f04bd0a06491'), 'type' => 'select', 'options' => ['once', 'daily', 'weekly', 'monthly'], 'required' => true],
            'scheduled_at' => ['label' => app_text('auto.k_854ba1dc86aa'), 'type' => 'datetime-local', 'nullable' => true],
            'status' => ['label' => app_text('auto.k_f7f293b5c58c'), 'type' => 'select', 'options' => ['draft', 'scheduled', 'sent', 'cancelled'], 'required' => true],
        ],
    ],
    'content' => [
        'title' => app_text('auto.k_5e30f01694b5'),
        'table' => 'content_posts',
        'columns' => ['id', 'title', 'owner_type', 'owner_id', 'status', 'publish_at', 'created_by'],
        'fields' => [
            'owner_type' => ['label' => app_text('integrations.owner_type'), 'type' => 'select', 'options' => ['reseller', 'manager'], 'nullable' => true],
            'owner_id' => ['label' => app_text('integrations.owner_id'), 'type' => 'number', 'nullable' => true],
            'content_type' => ['label' => app_text('auto.k_ef19578bced0'), 'type' => 'select', 'options' => ['article', 'image', 'pdf', 'video', 'link'], 'required' => true],
            'section_type' => ['label' => 'Раздел мини-сайта', 'type' => 'select', 'options' => ['general', 'story', 'result', 'promotion', 'giveaway', 'program', 'marathon'], 'required' => true],
            'title' => ['label' => app_text('auto.k_a8504d513adf'), 'required' => true],
            'short_text' => ['label' => app_text('auto.k_45cab8e7b9f1'), 'type' => 'textarea'],
            'full_text' => ['label' => app_text('auto.k_88a3ec931c4d'), 'type' => 'textarea'],
            'image_path' => ['label' => app_text('auto.k_56a1fd52891d'), 'type' => 'file', 'accept' => 'image/*'],
            'attachment_path' => ['label' => app_text('auto.k_1e51e67e49b3'), 'type' => 'file', 'accept' => 'application/pdf,video/mp4,image/*'],
            'video_url' => ['label' => app_text('auto.k_54fbfaf96a2d')],
            'button_text' => ['label' => app_text('auto.k_f9fd27363780')],
            'button_url' => ['label' => app_text('auto.k_668acad1ed4c')],
            'category_id' => ['label' => app_text('auto.k_1cf49d95b0ed'), 'type' => 'select', 'source' => 'product_categories', 'nullable' => true],
            'status' => ['label' => app_text('auto.k_f7f293b5c58c'), 'type' => 'select', 'options' => ['draft', 'published', 'hidden'], 'required' => true],
            'publish_at' => ['label' => app_text('auto.k_8ad0765b3c02'), 'type' => 'datetime-local', 'nullable' => true],
        ],
    ],
    'site_templates' => [
        'title' => 'Шаблоны мини-сайта',
        'table' => 'site_templates',
        'columns' => ['id', 'title', 'slug', 'description', 'owner_type', 'owner_id', 'profile_json', 'blocks_json', 'sort_order', 'is_active'],
        'fields' => [
            'title' => ['label' => 'Название', 'required' => true],
            'slug' => [
                'label' => 'Код шаблона',
                'required' => true,
                'hint' => 'Только латиница, цифры, дефис или подчёркивание.',
            ],
            'description' => ['label' => 'Описание', 'type' => 'textarea'],
            'profile_json' => [
                'label' => 'Первый экран',
                'type' => 'textarea',
                'required' => true,
                'default' => site_template_default_profile_json(),
                'rows' => 14,
                'hint' => 'JSON. Можно использовать {{name}}, {{role_label}}, {{phone}}, {{email}}.',
            ],
            'blocks_json' => [
                'label' => 'Блоки страницы',
                'type' => 'textarea',
                'default' => site_template_default_blocks_json(),
                'rows' => 14,
                'hint' => 'JSON-массив блоков мини-сайта.',
            ],
            'sort_order' => ['label' => app_text('auto.k_ed030118aad8'), 'type' => 'number', 'default' => 100],
            'is_active' => ['label' => app_text('auto.k_667904ef22a4'), 'type' => 'checkbox', 'default' => 1],
        ],
    ],
    'integrations' => [
        'title' => app_text('integrations.title'),
        'table' => 'messaging_integrations',
        'columns' => ['id', 'owner_type', 'owner_id', 'platform', 'title', 'external_id', 'is_default', 'callback_last_event_at', 'is_active'],
        'fields' => [
            'owner_type' => ['label' => app_text('integrations.owner_type'), 'type' => 'select', 'options' => ['reseller', 'manager'], 'required' => true],
            'owner_id' => ['label' => app_text('integrations.owner_id'), 'type' => 'number', 'required' => true],
            'platform' => ['label' => app_text('auto.k_89009febe5c6'), 'type' => 'select', 'options' => ['VK', 'OK', 'telegram', 'MAX'], 'required' => true],
            'title' => ['label' => app_text('auto.k_3de49828e86a'), 'required' => true],
            'external_id' => [
                'label' => app_text('integrations.external_id'),
                'help' => [
                    'title' => 'group_id',
                    'text' => 'В VK откройте Callback API. В сером блоке подтверждения скопируйте число из JSON после group_id.',
                    'image' => '/admin/uploads/help/vk-callback-group-id-marked.png',
                ],
            ],
            'access_token' => [
                'label' => app_text('integrations.access_token'),
                'type' => 'textarea',
                'help' => [
                    'title' => 'Ключ доступа',
                    'text' => 'В VK откройте «Дополнительно» -> «Работа с API» -> «Ключи доступа», создайте ключ и скопируйте строку вида vk1.a... в это поле.',
                    'image' => '/admin/uploads/help/vk-api-access-token-marked.jpg',
                ],
            ],
            'callback_confirmation_code' => [
                'label' => app_text('integrations.callback_confirmation_code'),
                'help' => [
                    'title' => 'Строка, которую должен вернуть сервер',
                    'text' => 'В VK на вкладке Callback API скопируйте строку после слов «Строка, которую должен вернуть сервер».',
                    'image' => '/admin/uploads/help/vk-callback-confirmation-marked.png',
                ],
            ],
            'callback_secret' => [
                'label' => app_text('integrations.callback_secret'),
                'default' => integration_callback_secret(),
                'help' => [
                    'title' => 'Секретный ключ',
                    'text' => 'SWPro генерирует этот ключ сам. Скопируйте его в VK в поле «Секретный ключ» и нажмите «Сохранить».',
                    'image' => '/admin/uploads/help/vk-callback-secret-marked.png',
                ],
            ],
            'callback_last_event_at' => ['label' => app_text('integrations.callback_last_event_at'), 'readonly' => true],
            'callback_last_error' => ['label' => app_text('integrations.callback_last_error'), 'type' => 'textarea', 'readonly' => true],
            'is_default' => [
                'label' => 'Стандартное сообщество',
                'type' => 'checkbox',
                'default' => 0,
                'hint' => 'Используется, если у лидера или консультанта ещё нет собственного готового сообщества VK.',
            ],
            'is_active' => ['label' => app_text('auto.k_667904ef22a4'), 'type' => 'checkbox', 'default' => 1],
        ],
    ],
    'legal_documents' => [
        'title' => 'Юридические документы',
        'table' => 'legal_documents',
        'columns' => ['id', 'document_type', 'title', 'version', 'is_required', 'is_active', 'updated_at'],
        'fields' => [
            'document_type' => [
                'label' => 'Тип документа',
                'type' => 'select',
                'options' => legal_document_types(),
                'required' => true,
            ],
            'title' => ['label' => 'Название', 'required' => true],
            'version' => ['label' => 'Версия', 'required' => true, 'default' => date('d.m.Y'), 'hint' => 'Русский формат даты: ДД.ММ.ГГГГ'],
            'body' => [
                'label' => 'Текст документа',
                'type' => 'textarea',
                'required' => true,
                'hint' => 'Единственный оператор данных — владелец SWPro. Переменные [SWPRO_NAME], [SWPRO_STATUS], [SWPRO_INN], [SWPRO_ADDRESS], [SWPRO_EMAIL], [SWPRO_PHONE], [SWPRO_SITE] и совместимые [OPERATOR_*] всегда подставляют глобальные реквизиты SWPro. Реквизиты лидера в документы клиентов не подставляются.',
            ],
            'is_required' => ['label' => 'Обязательный', 'type' => 'checkbox', 'default' => 1],
            'is_active' => ['label' => 'Активен', 'type' => 'checkbox', 'default' => 1],
        ],
    ],
];
