# Plesk > swpro.ru > Apache & nginx Settings > Additional Apache directives

<Directory "/var/www/vhosts/swpro.ru/httpdocs">
    Options -Indexes
    AllowOverride All
    Require all granted
</Directory>

<DirectoryMatch "^/var/www/vhosts/swpro.ru/httpdocs/(\.git|database|deploy|bot|admin/app)(/|$)">
    Require all denied
</DirectoryMatch>
