# Plesk > swpro.ru > Apache & nginx Settings > Additional nginx directives

location ~ ^/(\.git|database|deploy|bot|admin/app)(/|$) {
    deny all;
    return 404;
}

location ~ ^/(README\.md|\.env|.*\.sql|.*\.log)$ {
    deny all;
    return 404;
}
